#!/usr/bin/python3
import sys

def tonum(s):
    try:
        return int(s)
    except ValueError:
        try:
            return float(s)
        except ValueError:
            print(f"Error: Invalid input '{s}'", file=sys.stderr)
            exit(1)

ans = 0
for line in sys.stdin:
    line = line.rstrip()
    for num in line.split():
        ans += tonum(num)

print(ans)

