#!/usr/bin/python3
import sys

def tonum(s):
    try:
        return int(s)
    except:
        return float(s)

ans = 0
for line in sys.stdin:
    line = line.rstrip()
    for num in line.split():  # 各行の数値をスペースで分割して処理
        ans += tonum(num)

print(ans)

