name: Run Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: チェックアウトリポジトリ
        uses: actions/checkout@v3

      - name: 必要なファイルに実行権限を付与
        run: |
          chmod +x ./plus
          chmod +x ./average.txt
          chmod +x ./test.bash

      - name: ワークディレクトリの内容を確認
        run: |
          ls -la

      - name: 必要な環境をセットアップ
        run: |
          sudo apt-get update
          sudo apt-get install -y python3 python3-pip

      - name: テストを実行
        run: |
          set -e  # エラー発生時に中断
          bash -x ./test.bash

