name: test-kadai.py

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"
      - name: Run tests
        run: |
          chmod +x kadai.py
          chmod +x test.bash
          ./test.bash

