name: Run Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: チェックアウトリポジトリ
        uses: actions/checkout@v3

      - name: 必要なファイルに実行権限を付与
        run: |
          chmod +x ./plus
          chmod +x ./average.txt || true
          chmod +x ./min.txt
          chmod +x ./max.txt
          chmod +x ./test.bash # test.bashの権限も付与

      - name: 現在のディレクトリ確認
        run: pwd

      - name: ファイル一覧確認
        run: ls -la

      - name: テストを実行
        run: bash ./test.bash

      - name: エラー時のデバッグログを表示
        if: failure()
        run: |
          echo "テストに失敗しました。以下はデバッグ情報です："
          ls -la
          cat ./test.bash

