name: Run Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # リポジトリをチェックアウト
      - name: チェックアウトリポジトリ
        uses: actions/checkout@v3

      # 必要なファイルに実行権限を付与
      - name: 必要なファイルに実行権限を付与
        run: |
          chmod +x ./plus
          chmod +x ./average
          chmod +x ./min
          chmod +x ./max

      # テストを実行
      - name: テストを実行
        run: |
          bash ./test.bash || (echo "テストが失敗しました" && exit 1)

      # エラー時のログ確認（任意の追加ステップ）
      - name: エラー時のデバッグログを表示
        if: failure()
        run: |
          echo "テストが失敗しました。以下はデバッグ情報です:"
          cat ./test.bash
          ls -l

