name: Run Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: チェックアウトリポジトリ
        uses: actions/checkout@v3

      - name: 必要なファイルに実行権限を付与
        run: |
          chmod +x ./plus
          chmod +x ./average.txt || true
          chmod +x ./min.txt
          chmod +x ./max.txt
          chmod +x ./test.bash

      - name: テスト前のファイル確認
        run: ls -la

      - name: テストを実行
        run: |
          set -e
          bash -x ./test.bash

