name: Run Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: チェックアウトリポジトリ
        uses: actions/checkout@v3

      - name: 必要なファイルを確認
        run: ls -la

      - name: 必要なファイルに実行権限を付与
        run: |
          chmod +x ./plus
          chmod +x ./average.txt || true
          chmod +x ./min.txt || true
          chmod +x ./max.txt || true
          chmod +x ./test.bash

      - name: テストを実行
        run: |
          set -e  # エラー発生時に中断
          echo "Running tests with debug mode..."
          {
            bash -x ./test3.bash  # デバッグモードで実行
          } || {
            echo "::error::テストスクリプトの実行中にエラーが発生しました。"
            exit 1
          }

